title: Sistema de Elección Popular
email: ing.sanders@gmail.com
description: SEP es un sistema de elección popular pensado para el sufragio en instituciones educativas.
baseurl: ""
url: "https://www.sandersgutierrez.com"
twitter_username: sanderselnegro
github_username:  sandersgutierrez
author:
  name: Sanders Gutiérrez
  github: sandersgutierrez
  twitter: sanderselnegro

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
